### PR TITLE
Fixed the mweb safari popup picker cannot be full screen when the keyboard is displayed

### PR DESCRIPTION
**Pull request by hellohublot**
Issue: https://github.com/Expensify/App/issues/16081
Proposal: https://github.com/Expensify/App/issues/16081#issuecomment-1477345252
C+ Review: https://github.com/Expensify/App/issues/16081#issuecomment-1480384179
Expensify Review: https://github.com/Expensify/App/issues/16081#issuecomment-1494824244

When the keyboard is displayed, mwebSafari pops up a new picker and cannot calculate the correct screen height, causing the picker to not be full screen

We `dismiss` the keyboard in the `onPointerUp` first, and then the page can correctly display the size of the picker

### CODE REVIEW

**Comment by AndrewGable** [comment]
@s77rt - Can you comment here so I can assign you for review too? Thanks!

**Comment by s77rt** [comment]
Sure

**Comment by AndrewGable** [comment]
Weird - Doesn't look like I can assign you, but just double checking this looks good for your review? Then we can pull this change into package.json and do our checklist on the App PR.

**Comment by s77rt** [comment]
Yes the change looks good to me.

**Review by AndrewGable — APPROVED** [review]

**Pull request merged**
